name: fitflow
description: A fitness app with workout tracking and yoga routines.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  animated_background: ^2.0.0
  http: ^1.1.0
  provider: ^6.0.5
  youtube_player_iframe: ^4.0.4
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  ssl_pinning_plugin: ^2.0.0
  webview_flutter: ^4.0.0
  webview_flutter_android: ^3.0.0
  webview_flutter_platform_interface: ^2.0.0
  webview_flutter_web: ^0.2.3+4
  webview_flutter_wkwebview: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Circuit_Training.jpeg
    - assets/workout_animation.json
    - assets/yoga_animation.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
