// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvP-L3rK-eq03k_nUySZ6ViPT4gAdI6D0',
    appId: '1:1013360504179:web:b8d333009a415047ec2906',
    messagingSenderId: '1013360504179',
    projectId: 'fitflow-3bc6b',
    authDomain: 'fitflow-3bc6b.firebaseapp.com',
    storageBucket: 'fitflow-3bc6b.appspot.com',
    measurementId: 'G-TC67CD5NLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbZpYDIIJVXoBIMahbX4xOfS_xVVKomQ',
    appId: '1:1013360504179:android:c1f34e3236da87ceec2906',
    messagingSenderId: '1013360504179',
    projectId: 'fitflow-3bc6b',
    storageBucket: 'fitflow-3bc6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXcqyTJXmDJtDvOQoBtXeK4pBmqQ90uXU',
    appId: '1:1013360504179:ios:25d35a63b1929e73ec2906',
    messagingSenderId: '1013360504179',
    projectId: 'fitflow-3bc6b',
    storageBucket: 'fitflow-3bc6b.appspot.com',
    iosBundleId: 'com.example.firNFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXcqyTJXmDJtDvOQoBtXeK4pBmqQ90uXU',
    appId: '1:1013360504179:ios:25d35a63b1929e73ec2906',
    messagingSenderId: '1013360504179',
    projectId: 'fitflow-3bc6b',
    storageBucket: 'fitflow-3bc6b.appspot.com',
    iosBundleId: 'com.example.firNFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvP-L3rK-eq03k_nUySZ6ViPT4gAdI6D0',
    appId: '1:1013360504179:web:2c68b0a9225afc9fec2906',
    messagingSenderId: '1013360504179',
    projectId: 'fitflow-3bc6b',
    authDomain: 'fitflow-3bc6b.firebaseapp.com',
    storageBucket: 'fitflow-3bc6b.appspot.com',
    measurementId: 'G-8LESPSDL7B',
  );
}
